# Generated by Django 4.1.7 on 2023-02-20 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.CharField(max_length=20)),
                ('stock_name', models.CharField(max_length=50)),
                ('shares', models.FloatField()),
                ('price', models.FloatField()),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='orders',
            constraint=models.UniqueConstraint(fields=('user_email', 'timestamp', 'ticker'), name='unique_key_combination'),
        ),
    ]
